version: '3.3'
services:

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: kungfuproger/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/

  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: kungfuproger/foodgram:latest
    restart: always
    volumes:
      - static_volume:/app/backend_static/
      - media_volume:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env
    command: gunicorn --bind 0:8000 foodgram.wsgi:application

  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/backend_static/
      - media_volume:/var/html/backend_media/
    depends_on:
      - backend

volumes:
  db_data:
  static_volume:
  media_volume:
